spring.application.name=lifeofpaw
server.port=8889

spring.datasource.url=jdbc:postgresql://dpg-d97o2lurnols738lsq1g-a.singapore-postgres.render.com:5432/lifeofpaw?ssl=true&sslmode=require
spring.datasource.username=anurag
spring.datasource.password=byW8V0cyLyBumDO0UNQ7lJDU7fSHmEPa
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.connection.autocommit=true
spring.jpa.properties.hibernate.transaction.coordinator_class=jdbc

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5



file.upload-dir=uploads


logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.orm.jdbc.bind=WARN


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB